---
- name: configure test server
  hosts: prod-server
  become: true
  
  tasks:
  - name: update repo
    command: sudo apt update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 docker9239/insure-me-app:1.0
